[package]
name = "helix"
version = "0.1.0"
authors = ["Godhuda <engineering+godhuda@tilde.io>"]
license = "MIT/Apache-2.0"

[workspace]

members = ["crates/libcruby-sys", "examples/console", "examples/membership", "examples/turbo_blank"]

[dependencies]
libc = "0.2.0"

[dependencies.cslice]
version = "0.2"

[dependencies.libcruby-sys]
path = "crates/libcruby-sys"
